/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AgentLifetime = "ephemeral" | "registered";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type ArtifactState = "deleted" | "expiring" | "live";

export type DataClass = "internal" | "regulated";

export type DurabilityTier = "relaxed" | "strict";

export type EffectClass = "cacheable" | "compensatable" | "essential" | "human_approval_required" | "idempotent" | "non_idempotent" | "read_only" | "transactional";

export type EnforcementLevel = "agent" | "mcp_server" | "model" | "namespace" | "org" | "peer" | "speech_provider" | "tenant" | "tool" | "worker_pool";

export type Environment = "production" | "staging";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type GrantSource = "service" | "user";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type InteractionKind = "approval" | "authentication" | "clarification" | "escalation" | "question";

export type InteractionStatus = "cancelled" | "expired" | "pending" | "resolved";

export type LineageNodeKind = "artifact" | "interaction" | "memory" | "model_output" | "peer_result" | "run" | "step" | "tool_invocation" | "user_input";

export type McpTransport = "stdio" | "streamable_http";

export type MemoryProvenance = "artifact" | "consolidated" | "model_output" | "peer_result" | "tool_output" | "user_input";

export type MemoryScope = "agent" | "org" | "run" | "tenant" | "thread" | "user";

export type MemoryTier = "conversational" | "episodic" | "external" | "procedural" | "semantic" | "working";

export type Numeric = ColumnType<string, number | string, number | string>;

export type PeerBinding = "inbound" | "local" | "remote";

export type PrincipalKind = "human" | "service" | "workload";

export type RegistryStatus = "active" | "deprecated" | "disabled";

export type Residency = "external" | "internal";

export type RunInitiator = "api" | "peer" | "schedule" | "shadow" | "sub_agent" | "trigger";

export type RunStatus = "cancelled" | "checkpointed" | "completed" | "dead_letter" | "failed" | "queued" | "running" | "tool_execution" | "waiting";

export type SaturationPolicy = "queue" | "shed" | "throttle";

export type SpeechKind = "stt" | "tts";

export type StepKind = "context_op" | "delegation" | "interaction" | "memory_op" | "model_call" | "peer_call" | "tool_call";

export type StepStatus = "cancelled" | "compensated" | "failed" | "pending" | "running" | "succeeded";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type ToolOrigin = "function" | "http" | "mcp" | "native" | "peer";

export type Transport = "poll" | "sse" | "voice_telephony" | "voice_webrtc" | "webhook";

export type TriggerType = "callback" | "event" | "http" | "schedule" | "webhook";

export interface A2aPushConfigs {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  run_id: string;
  token_ref: string | null;
  url: string;
}

export interface AdmissionDecisions {
  agent_version_id: string | null;
  approved: boolean;
  caller_principal_id: string;
  checks: Generated<ColumnType<unknown, string, string>>;
  decided_at: Generated<Timestamp>;
  id: Generated<string>;
  namespace_id: string;
  org_id: string;
  rejection_reasons: Generated<ColumnType<unknown, string, string>>;
  spec_hash: string;
}

export interface Agents {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  expose_as_peer: Generated<boolean>;
  id: Generated<string>;
  name: string;
  namespace_id: string;
  org_id: string;
  owner: string;
  updated_at: Generated<Timestamp>;
}

export interface AgentVersionCollections {
  agent_version_id: string;
  collection_id: string;
  namespace_id: string;
}

export interface AgentVersionMcpServers {
  agent_version_id: string;
  allow_sampling: Generated<boolean>;
  allowed_tools: string[];
  mcp_server_id: string;
}

export interface AgentVersionPeers {
  agent_version_id: string;
  alias: string;
  peer_id: string;
}

export interface AgentVersions {
  agent_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  data_class: Generated<DataClass>;
  durability: Generated<DurabilityTier>;
  id: Generated<string>;
  lifetime: AgentLifetime;
  max_concurrent_runs: number | null;
  max_cost_micros: Int8 | null;
  max_retries: Generated<number>;
  max_steps: number | null;
  max_tokens: Int8 | null;
  model_id: string;
  namespace_id: string;
  on_saturation: Generated<SaturationPolicy>;
  org_id: string;
  overridable_fields: Generated<string[]>;
  policy_version_id: string | null;
  prompt_version_id: string | null;
  run_timeout_ms: Generated<number>;
  spec: ColumnType<unknown, string, string>;
  spec_hash: string;
  step_timeout_ms: Generated<number>;
  tenant_isolation: Generated<string>;
  transport: Generated<Transport>;
  version: number | null;
  workload_identity_id: string;
}

export interface AgentVersionSkills {
  agent_version_id: string;
  namespace_id: string;
  ord: number;
  skill_version_id: string;
}

export interface AgentVersionSpeech {
  agent_version_id: string;
  speech_kind: SpeechKind;
  speech_provider_id: string;
}

export interface AgentVersionSubAgents {
  agent_version_id: string;
  alias: string;
  namespace_id: string;
  sub_agent_id: string;
}

export interface AgentVersionTools {
  agent_version_id: string;
  cache_scope: string | null;
  cache_ttl_seconds: number | null;
  compensation_tool_id: string | null;
  effects: ArrayType<EffectClass>;
  fixed_args: Generated<ColumnType<unknown, string, string>>;
  idempotency_key_tpl: string | null;
  tool_id: string;
}

export interface Artifacts {
  content_hash: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  encryption_key_ref: string;
  expires_at: Timestamp | null;
  id: Generated<string>;
  legal_hold: Generated<boolean>;
  media_type: string;
  metadata: Generated<ColumnType<unknown, string, string>>;
  namespace_id: string;
  org_id: string;
  parent_artifact_id: string | null;
  produced_by_run_id: string | null;
  produced_by_step_id: string | null;
  retention_policy: string | null;
  size_bytes: Int8;
  state: Generated<ArtifactState>;
  storage_uri: string;
  tenant_ref: string;
  thread_id: string | null;
  version: Generated<number>;
}

export interface AuditLog {
  action: string;
  actor_principal_id: string;
  detail: Generated<ColumnType<unknown, string, string>>;
  id: Generated<string>;
  namespace_id: string | null;
  occurred_at: Generated<Timestamp>;
  on_behalf_of_principal_id: string | null;
  org_id: string;
  outcome: string;
  reason: string | null;
  resource_id: string | null;
  resource_kind: string;
  source_ip: string | null;
  tenant_ref: string | null;
}

export interface BackpressurePolicies {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: EnforcementLevel;
  max_concurrency: number | null;
  max_rate_per_sec: Numeric | null;
  on_saturation: SaturationPolicy;
  org_id: string;
  queue_depth_limit: number | null;
  scope_ref: string;
}

export interface Budgets {
  id: Generated<string>;
  level: EnforcementLevel;
  limit_micros: Int8;
  org_id: string;
  period: "hour" | "day" | "month" | "total";
  period_started_at: Generated<Timestamp>;
  resets_at: Timestamp | null;
  scope_ref: string;
  spent_micros: Generated<Int8>;
}

export interface CapabilityGrants {
  constraints: Generated<ColumnType<unknown, string, string>>;
  expires_at: Timestamp | null;
  grant_source: GrantSource;
  granted_at: Generated<Timestamp>;
  granted_by: string;
  grantee_principal_id: string | null;
  id: Generated<string>;
  namespace_id: string | null;
  org_id: string;
  resource_id: string;
  resource_kind: string;
  revoked_at: Timestamp | null;
  tenant_ref: string | null;
}

export interface Checkpoints {
  created_at: Generated<Timestamp>;
  durability: DurabilityTier;
  id: Generated<string>;
  parent_checkpoint_id: string | null;
  run_id: string;
  schema_version: number;
  state: ColumnType<unknown, string, string> | null;
  state_artifact_id: string | null;
  state_hash: string;
  step_seq: number;
}

export interface CredentialGrants {
  audience: string;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  on_behalf_of_principal_id: string | null;
  org_id: string;
  revoked_at: Timestamp | null;
  run_id: string;
  scopes: string[];
  step_id: string | null;
  tenant_ref: string | null;
  token_id: string;
  workload_identity_id: string;
}

export interface DeadLetters {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  attempts: number;
  created_at: Generated<Timestamp>;
  error: ColumnType<unknown, string, string>;
  id: Generated<string>;
  last_worker: string | null;
  reason: string;
  replayed_run_id: string | null;
  run_id: string;
  step_id: string | null;
}

export interface Deployments {
  agent_id: string;
  agent_version_id: string;
  canary_percent: Generated<number>;
  created_at: Generated<Timestamp>;
  environment: Environment;
  gate_overridden_by: string | null;
  gate_override_reason: string | null;
  id: Generated<string>;
  promoted_at: Timestamp | null;
  promoted_by: string | null;
  promotion_eval_run_id: string | null;
  shadow_from_version_id: string | null;
  state: Generated<"active" | "rolling" | "rolled_back" | "retired">;
}

export interface EvalCaseResults {
  detail: ColumnType<unknown, string, string> | null;
  eval_case_id: string;
  eval_run_id: string;
  passed: boolean;
  run_id: string | null;
  score: Numeric | null;
  trial: Generated<number>;
}

export interface EvalCases {
  ab_comparable: Generated<boolean>;
  eval_suite_id: string;
  expectation: ColumnType<unknown, string, string>;
  grader: Generated<"exact" | "contains" | "not_contains" | "regex" | "json_path" | "budget" | "llm_judge">;
  id: Generated<string>;
  input: ColumnType<unknown, string, string>;
  name: string;
  weight: Generated<number>;
}

export interface EvalRuns {
  agent_version_id: string;
  baseline_eval_run_id: string | null;
  cases_errored: Generated<number>;
  cases_passed: Generated<number>;
  cases_total: Generated<number>;
  ended_at: Timestamp | null;
  eval_suite_id: string;
  executed_version_id: string | null;
  id: Generated<string>;
  mechanism_enabled: boolean | null;
  min_score: Numeric | null;
  p50_latency_ms: number | null;
  passed: boolean | null;
  score: Numeric | null;
  score_stderr: Numeric | null;
  started_at: Generated<Timestamp>;
  total_cost_micros: Generated<Int8>;
  verdict: "passed" | "failed" | "mechanism_justified" | "mechanism_not_justified" | "inconclusive" | null;
}

export interface EvalSuites {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  mechanism_under_test: "summarization" | "compaction" | "memory_tiers" | "planning_scaffold" | "sub_agents" | "retrieval" | "eviction" | "skills" | "knowledge" | "model_cache" | "peers" | "none" | null;
  min_mechanism_delta: Generated<Numeric>;
  min_score: Generated<Numeric>;
  namespace_id: string;
  org_id: string;
  ref: string;
  trials_per_case: Generated<number>;
}

export interface Events {
  agent_version_id: string;
  causation_id: string | null;
  correlation_id: string | null;
  delegation_chain: Generated<ColumnType<unknown, string, string>>;
  event_type: string;
  id: Generated<string>;
  namespace_id: string;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  parent_run_id: string | null;
  payload: ColumnType<unknown, string, string>;
  principal_id: string | null;
  protocol_metadata: Generated<ColumnType<unknown, string, string>>;
  run_id: string;
  schema_version: number;
  seq: Int8;
  span_id: string | null;
  step_id: string | null;
  tenant_ref: string;
  thread_id: string;
  trace_id: string | null;
}

export interface EventSchemaVersions {
  event_type: string;
  introduced_at: Generated<Timestamp>;
  json_schema: ColumnType<unknown, string, string>;
  retired_at: Timestamp | null;
  schema_version: number;
  upcaster_ref: string | null;
}

export interface Feedback {
  agent_version_id: string;
  comment: string | null;
  correction: ColumnType<unknown, string, string> | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  interaction_id: string | null;
  label: string | null;
  namespace_id: string;
  org_id: string;
  principal_id: string | null;
  rating: number | null;
  run_id: string | null;
  tenant_ref: string;
  thread_id: string | null;
}

export interface Interactions {
  created_at: Generated<Timestamp>;
  delegation_chain: Generated<ColumnType<unknown, string, string>>;
  expires_at: Timestamp;
  id: Generated<string>;
  kind: InteractionKind;
  namespace_id: string;
  org_id: string;
  originating_principal_id: string | null;
  originating_run_id: string | null;
  prompt: ColumnType<unknown, string, string>;
  required_authorization: Generated<ColumnType<unknown, string, string>>;
  resolved_at: Timestamp | null;
  responder_principal_id: string | null;
  response: ColumnType<unknown, string, string> | null;
  response_schema: ColumnType<unknown, string, string> | null;
  run_id: string;
  status: Generated<InteractionStatus>;
  step_id: string | null;
  tenant_ref: string;
  thread_id: string;
}

export interface KnowledgeChunks {
  collection_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  document_id: string;
  embedding: string | null;
  id: Generated<string>;
  ord: number;
}

export interface KnowledgeCollections {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  dimensions: number;
  embedder_id: string;
  id: Generated<string>;
  name: string;
  namespace_id: string;
  org_id: string;
  status: Generated<RegistryStatus>;
  updated_at: Generated<Timestamp>;
}

export interface KnowledgeDocuments {
  body: string;
  chunk_count: Generated<number>;
  collection_id: string;
  content_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  indexed_at: Timestamp | null;
  metadata: Generated<ColumnType<unknown, string, string>>;
  org_id: string;
  source_uri: string | null;
  title: string | null;
}

export interface LanggraphCheckpoints {
  checkpoint: Buffer;
  checkpoint_id: string;
  checkpoint_ns: Generated<string>;
  created_at: Generated<Timestamp>;
  metadata: Generated<ColumnType<unknown, string, string>>;
  org_id: string;
  parent_checkpoint_id: string | null;
  thread_id: string;
  type: string | null;
}

export interface LanggraphCheckpointWrites {
  channel: string;
  checkpoint_id: string;
  checkpoint_ns: Generated<string>;
  idx: number;
  org_id: string;
  task_id: string;
  thread_id: string;
  type: string | null;
  value: Buffer | null;
}

export interface LineageEdges {
  derived_id: string;
  derived_kind: LineageNodeKind;
  id: Generated<string>;
  observed_at: Generated<Timestamp>;
  org_id: string;
  relation: string;
  run_id: string | null;
  source_id: string;
  source_kind: LineageNodeKind;
  tenant_ref: string;
}

export interface McpServerApprovals {
  approved_at: Generated<Timestamp>;
  approved_by: string;
  id: Generated<string>;
  mcp_server_id: string;
  namespace_id: string;
  revoked_at: Timestamp | null;
  tenant_ref: string | null;
}

export interface McpServers {
  allow_sampling: Generated<boolean>;
  command: string[] | null;
  created_at: Generated<Timestamp>;
  endpoint_url: string | null;
  id: Generated<string>;
  mcp_transport: McpTransport;
  name: string;
  namespace_id: string;
  org_id: string;
  protocol_revision: string;
  rate_limit_qps: number | null;
  residency: Residency;
  status: Generated<RegistryStatus>;
}

export interface McpServerTools {
  approved_at: Timestamp | null;
  approved_by: string | null;
  definition: ColumnType<unknown, string, string>;
  definition_hash: string;
  first_seen_at: Generated<Timestamp>;
  id: Generated<string>;
  mcp_server_id: string;
  superseded_at: Timestamp | null;
  tool_name: string;
}

export interface MemoryEmbeddings {
  created_at: Generated<Timestamp>;
  dimensions: number;
  embedding: string;
  memory_id: string;
  model_id: string;
}

export interface MemoryRecords {
  access_count: Generated<number>;
  artifact_id: string | null;
  consolidated_from: Generated<string[]>;
  content: string | null;
  created_at: Generated<Timestamp>;
  delivered: boolean | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  last_accessed_at: Timestamp | null;
  namespace_id: string;
  org_id: string;
  played_offset_ms: number | null;
  provenance: MemoryProvenance;
  salience: Generated<number>;
  scope: MemoryScope;
  scope_agent_id: string | null;
  scope_run_id: string | null;
  scope_thread_id: string | null;
  scope_user_id: string | null;
  shared: Generated<boolean>;
  sharing_policy_id: string | null;
  source_peer_id: string | null;
  source_run_id: string | null;
  source_step_id: string | null;
  source_tenant_ref: string | null;
  structured: ColumnType<unknown, string, string> | null;
  superseded_by: string | null;
  tenant_ref: string;
  tier: MemoryTier;
  trusted: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface MemorySharingPolicies {
  approved_at: Generated<Timestamp>;
  approved_by: string;
  enabled: Generated<boolean>;
  id: Generated<string>;
  namespace_id: string;
  org_id: string;
  redaction_policy: string;
  revoked_at: Timestamp | null;
  tiers: ArrayType<MemoryTier>;
}

export interface Models {
  /**
   * Provider endpoint. A LiteLLM proxy is modelled as an openai-compatible provider with its own base_url.
   */
  base_url: string | null;
  capabilities: Generated<ColumnType<unknown, string, string>>;
  context_window_tokens: number | null;
  created_at: Generated<Timestamp>;
  /**
   * Name resolved by the credential broker against the secret store. Never the secret itself.
   */
  credential_ref: string | null;
  fallback_model_id: string | null;
  id: Generated<string>;
  input_cost_micros_per_1k: Int8 | null;
  max_output_tokens: number | null;
  org_id: string;
  output_cost_micros_per_1k: Int8 | null;
  provider: string;
  provider_model_id: string;
  ref: string;
  region: string | null;
  residency: Residency;
  status: Generated<RegistryStatus>;
}

export interface Namespaces {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  owner_contact: string;
  owning_team: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface Orgs {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface Outbox {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  destination: string;
  id: Generated<string>;
  idempotency_key: string;
  last_error: ColumnType<unknown, string, string> | null;
  next_attempt_at: Generated<Timestamp>;
  payload: ColumnType<unknown, string, string>;
  run_id: string;
  sent_at: Timestamp | null;
  status: Generated<string>;
  step_id: string | null;
  tool_invocation_id: string | null;
}

export interface Peers {
  agent_card: ColumnType<unknown, string, string> | null;
  binding: PeerBinding;
  card_fetched_at: Timestamp | null;
  card_signature: string | null;
  card_verified_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  endpoint_url: string | null;
  failure_mode: Generated<"contain" | "propagate">;
  id: Generated<string>;
  inbound_trust: Generated<"self" | "delegated_identity">;
  local_agent_id: string | null;
  name: string;
  namespace_id: string;
  org_id: string;
  protocol_version: string;
  public_key: string | null;
  reply_mode: Generated<"task" | "message">;
  residency: Residency;
  status: Generated<RegistryStatus>;
  timeout_ms: Generated<number>;
}

export interface PeerTasks {
  binding: "local" | "remote";
  child_run_id: string | null;
  created_at: Generated<Timestamp>;
  error: ColumnType<unknown, string, string> | null;
  id: Generated<string>;
  last_observed_at: Timestamp | null;
  org_id: string;
  peer_id: string;
  remote_context_id: string | null;
  remote_task_id: string | null;
  run_id: string;
  state: Generated<"submitted" | "working" | "input_required" | "completed" | "failed" | "cancelled">;
  step_id: string;
}

export interface Policies {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  owner: string;
  ref: string;
}

export interface PolicyVersions {
  approved_at: Timestamp | null;
  approved_by: string | null;
  content_hash: string;
  created_at: Generated<Timestamp>;
  document: ColumnType<unknown, string, string>;
  id: Generated<string>;
  policy_id: string;
  version: number;
}

export interface Principals {
  created_at: Generated<Timestamp>;
  disabled_at: Timestamp | null;
  display_name: string | null;
  id: Generated<string>;
  kind: PrincipalKind;
  org_id: string;
  subject: string;
}

export interface PromotionGates {
  agent_id: string;
  allow_override: Generated<boolean>;
  created_at: Generated<Timestamp>;
  environment: Environment;
  eval_suite_id: string;
  id: Generated<string>;
  min_score: Generated<Numeric>;
  org_id: string;
}

export interface Prompts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  namespace_id: string;
  org_id: string;
  owner: string;
  ref: string;
}

export interface PromptVersions {
  approved_at: Timestamp | null;
  approved_by: string | null;
  body: string;
  content_hash: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  prompt_id: string;
  version: number;
}

export interface RunQueue {
  attempts: Generated<number>;
  enqueued_at: Generated<Timestamp>;
  heartbeat_at: Timestamp | null;
  lease_epoch: Generated<Int8>;
  lease_expires_at: Timestamp | null;
  lease_owner: string | null;
  priority: Generated<number>;
  run_id: string;
  visible_at: Generated<Timestamp>;
  worker_pool: Generated<string>;
}

export interface Runs {
  agent_version_id: string;
  attempt: Generated<number>;
  authorizing_human_id: string | null;
  caller_principal_id: string;
  causation_id: string | null;
  correlation_id: string | null;
  cost_micros: Generated<Int8>;
  created_at: Generated<Timestamp>;
  deadline_at: Timestamp | null;
  delegation_chain: Generated<ColumnType<unknown, string, string>>;
  delegation_depth: Generated<number>;
  delivery: ColumnType<unknown, string, string> | null;
  durability: DurabilityTier;
  ended_at: Timestamp | null;
  error: ColumnType<unknown, string, string> | null;
  forked_from_checkpoint_id: string | null;
  id: Generated<string>;
  idempotency_key: string | null;
  initiator: RunInitiator;
  input: ColumnType<unknown, string, string> | null;
  input_artifact_id: string | null;
  input_tokens: Generated<Int8>;
  last_checkpoint_id: string | null;
  last_event_seq: Generated<Int8>;
  max_cost_micros: Int8 | null;
  namespace_id: string;
  on_behalf_of_principal_id: string | null;
  org_id: string;
  output: ColumnType<unknown, string, string> | null;
  output_artifact_id: string | null;
  output_tokens: Generated<Int8>;
  parent_run_id: string | null;
  queued_at: Generated<Timestamp>;
  root_run_id: string | null;
  shadow_of_run_id: string | null;
  started_at: Timestamp | null;
  status: Generated<RunStatus>;
  step_count: Generated<number>;
  tenant_id: string | null;
  tenant_ref: string;
  thread_id: string;
  trace_id: string | null;
  trigger_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  checksum: string;
  version: string;
}

export interface Skills {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  namespace_id: string;
  org_id: string;
}

export interface SkillVersionCollections {
  collection_id: string;
  namespace_id: string;
  skill_version_id: string;
}

export interface SkillVersions {
  content_uri: string | null;
  id: Generated<string>;
  instructions: string | null;
  namespace_id: string;
  org_id: string;
  published_at: Generated<Timestamp>;
  published_by: string | null;
  skill_id: string;
  spec_hash: string;
  status: Generated<RegistryStatus>;
  version: number;
  when_to_use: string | null;
}

export interface SkillVersionTools {
  effects: ArrayType<EffectClass>;
  skill_version_id: string;
  tool_id: string;
}

export interface SpeechProviders {
  cost_tier: string | null;
  id: Generated<string>;
  languages: Generated<string[]>;
  max_concurrent_sessions: number | null;
  name: string;
  org_id: string;
  region: string | null;
  residency: Residency;
  speech_kind: SpeechKind;
  status: Generated<RegistryStatus>;
}

export interface Steps {
  agent_version_id: string | null;
  attempt: Generated<number>;
  cached_input_tokens: number | null;
  checkpoint_id: string | null;
  cost_micros: Int8 | null;
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  error: ColumnType<unknown, string, string> | null;
  fallback_from_model_id: string | null;
  id: Generated<string>;
  input: ColumnType<unknown, string, string> | null;
  input_artifact_id: string | null;
  input_tokens: number | null;
  kind: StepKind;
  latency_ms: number | null;
  model_id: string | null;
  namespace_id: string;
  org_id: string;
  output: ColumnType<unknown, string, string> | null;
  output_artifact_id: string | null;
  output_tokens: number | null;
  parent_step_id: string | null;
  prompt_version_id: string | null;
  run_id: string;
  seq: number;
  span_id: string | null;
  started_at: Timestamp | null;
  status: Generated<StepStatus>;
  tenant_ref: string;
  trace_id: string | null;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  data_class: Generated<DataClass>;
  display_name: string | null;
  id: Generated<string>;
  namespace_id: string;
  org_id: string;
  residency_region: string | null;
  tenant_ref: string;
}

export interface Threads {
  agent_id: string | null;
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  external_ref: string | null;
  id: Generated<string>;
  metadata: Generated<ColumnType<unknown, string, string>>;
  namespace_id: string;
  org_id: string;
  status: Generated<string>;
  tenant_id: string | null;
  tenant_ref: string;
  title: string | null;
  updated_at: Generated<Timestamp>;
  user_principal_id: string | null;
}

export interface ToolInvocations {
  attempt: Generated<number>;
  authorized_principal_id: string | null;
  capability_decision: Generated<ColumnType<unknown, string, string>>;
  compensates_invocation_id: string | null;
  created_at: Generated<Timestamp>;
  credential_grant_id: string | null;
  definition_hash: string | null;
  effects: ArrayType<EffectClass>;
  ended_at: Timestamp | null;
  error: ColumnType<unknown, string, string> | null;
  id: Generated<string>;
  idempotency_key: string | null;
  interaction_id: string | null;
  latency_ms: number | null;
  namespace_id: string;
  org_id: string;
  origin: ToolOrigin;
  protocol_metadata: Generated<ColumnType<unknown, string, string>>;
  request: ColumnType<unknown, string, string> | null;
  request_artifact_id: string | null;
  response: ColumnType<unknown, string, string> | null;
  response_artifact_id: string | null;
  run_id: string;
  sandbox_instance_id: string | null;
  sandbox_profile: string;
  started_at: Timestamp | null;
  status: Generated<StepStatus>;
  step_id: string;
  tenant_ref: string;
  thread_id: string;
  tool_id: string;
  tool_version: number;
}

export interface Tools {
  arg_placement: "query" | "body" | "none" | null;
  arg_wrapper_key: string | null;
  code_runtime: "node" | "python" | null;
  code_source: string | null;
  created_at: Generated<Timestamp>;
  credential_ref: string | null;
  default_effects: ArrayType<EffectClass>;
  definition_hash: string | null;
  description: string | null;
  endpoint_url: string | null;
  http_method: Generated<"GET" | "POST" | "PUT" | "PATCH" | "DELETE">;
  id: Generated<string>;
  input_schema: ColumnType<unknown, string, string>;
  max_retries: Generated<number>;
  mcp_server_id: string | null;
  mcp_tool_name: string | null;
  namespace_id: string;
  org_id: string;
  origin: ToolOrigin;
  output_schema: ColumnType<unknown, string, string> | null;
  path_template: string | null;
  ref: string;
  residency: Residency;
  sandbox_profile: string;
  spec_hash: string | null;
  static_headers: Generated<ColumnType<unknown, string, string>>;
  status: Generated<RegistryStatus>;
  template_id: string | null;
  timeout_ms: Generated<number>;
  version: Generated<number>;
}

export interface ToolTemplates {
  allowed_methods: Generated<string[]>;
  created_at: Generated<Timestamp>;
  credential_ref: string | null;
  default_effects: ArrayType<EffectClass>;
  description: string | null;
  endpoint_url: string;
  id: Generated<string>;
  max_instances: Generated<number>;
  max_retries: Generated<number>;
  namespace_id: string;
  org_id: string;
  path_prefix: string;
  ref: string;
  residency: Residency;
  sandbox_profile: string;
  static_headers: Generated<ColumnType<unknown, string, string>>;
  status: Generated<RegistryStatus>;
  timeout_ms: Generated<number>;
  version: Generated<number>;
}

export interface TraceExportCursor {
  exported_through: Timestamp;
  id: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface Triggers {
  agent_id: string;
  config: Generated<ColumnType<unknown, string, string>>;
  created_at: Generated<Timestamp>;
  cron_expression: string | null;
  enabled: Generated<boolean>;
  event_source: string | null;
  event_type: string | null;
  id: Generated<string>;
  pinned_version_id: string | null;
  tenant_ref: string | null;
  timezone: Generated<string>;
  trigger_type: TriggerType;
  webhook_path: string | null;
}

export interface UsageLedger {
  agent_version_id: string | null;
  cached_input_tokens: Generated<Int8>;
  cost_micros: Generated<Int8>;
  id: Generated<string>;
  input_tokens: Generated<Int8>;
  kind: string;
  model_id: string | null;
  namespace_id: string;
  occurred_at: Generated<Timestamp>;
  org_id: string;
  output_tokens: Generated<Int8>;
  provider: string | null;
  quantity: Generated<Numeric>;
  run_id: string | null;
  step_id: string | null;
  tenant_ref: string;
}

export interface DB {
  a2a_push_configs: A2aPushConfigs;
  admission_decisions: AdmissionDecisions;
  agent_version_collections: AgentVersionCollections;
  agent_version_mcp_servers: AgentVersionMcpServers;
  agent_version_peers: AgentVersionPeers;
  agent_version_skills: AgentVersionSkills;
  agent_version_speech: AgentVersionSpeech;
  agent_version_sub_agents: AgentVersionSubAgents;
  agent_version_tools: AgentVersionTools;
  agent_versions: AgentVersions;
  agents: Agents;
  artifacts: Artifacts;
  audit_log: AuditLog;
  backpressure_policies: BackpressurePolicies;
  budgets: Budgets;
  capability_grants: CapabilityGrants;
  checkpoints: Checkpoints;
  credential_grants: CredentialGrants;
  dead_letters: DeadLetters;
  deployments: Deployments;
  eval_case_results: EvalCaseResults;
  eval_cases: EvalCases;
  eval_runs: EvalRuns;
  eval_suites: EvalSuites;
  event_schema_versions: EventSchemaVersions;
  events: Events;
  feedback: Feedback;
  interactions: Interactions;
  knowledge_chunks: KnowledgeChunks;
  knowledge_collections: KnowledgeCollections;
  knowledge_documents: KnowledgeDocuments;
  langgraph_checkpoint_writes: LanggraphCheckpointWrites;
  langgraph_checkpoints: LanggraphCheckpoints;
  lineage_edges: LineageEdges;
  mcp_server_approvals: McpServerApprovals;
  mcp_server_tools: McpServerTools;
  mcp_servers: McpServers;
  memory_embeddings: MemoryEmbeddings;
  memory_records: MemoryRecords;
  memory_sharing_policies: MemorySharingPolicies;
  models: Models;
  namespaces: Namespaces;
  orgs: Orgs;
  outbox: Outbox;
  peer_tasks: PeerTasks;
  peers: Peers;
  policies: Policies;
  policy_versions: PolicyVersions;
  principals: Principals;
  promotion_gates: PromotionGates;
  prompt_versions: PromptVersions;
  prompts: Prompts;
  run_queue: RunQueue;
  runs: Runs;
  schema_migrations: SchemaMigrations;
  skill_version_collections: SkillVersionCollections;
  skill_version_tools: SkillVersionTools;
  skill_versions: SkillVersions;
  skills: Skills;
  speech_providers: SpeechProviders;
  steps: Steps;
  tenants: Tenants;
  threads: Threads;
  tool_invocations: ToolInvocations;
  tool_templates: ToolTemplates;
  tools: Tools;
  trace_export_cursor: TraceExportCursor;
  triggers: Triggers;
  usage_ledger: UsageLedger;
}
